### ISSUE TITLE
Allow named items, raters and ratings

### ISSUE THREAD

**Issue by StaffanBetner** [jeffreypullin/rater#154]
It would be useful to allow more than integer values inputs, such as named items, raters and ratings.

**Comment by jeffreypullin** [comment]
Hi Staffan, 

Thanks for opening an issue. I completely agree, indeed this feature request has been raised before see: #144 

Because of the interest in this it will be at the absolute top of my todo list next time I work on {rater}. (Around two weeks away at the earliest.)

Having said that this issue is technically a duplicate so I will close it now. Thanks for opening it though!

Best, 
Jeffrey

**Comment by StaffanBetner** [comment]
Oh, good! Didn't see that one!
