### ISSUE TITLE
Change point_estimates to return real z values

### ISSUE THREAD

**Issue by jeffreypullin** [jeffreypullin/rater#77]
And introduce a new function (name TBD) to return the posterior class probabilities.

Some possibilites for the name of the new function:

* `class_posterior_distribution()` - I would prefer to the name to start with posterior for consistency with `posterior_samples` and `posterior_interval`
* `posterior_class_probabilities` - Probably too long
* `posterior_class_probs`

We should ensure that the method for producing z values from the probabilities is featured prominently in the documentation and that the documentation links to the function to return the probabilities. 

cc @dvukcevic Thoughts on the name?

**Comment by dvukcevic** [comment]
Perhaps best to avoid the word 'posterior' so that the function still makes sense in optimisation mode?

If so, we could go with something like `class_probabilities()` and it will still be a reasonable length?

**Comment by jeffreypullin** [comment]
Perhaps I'm being dense, but wouldn't the probabilities still be part of a posterior distribution even in optimization mode?

**Comment by dvukcevic** [comment]
Yes...sort of...but not really.  :-)

I think what you get is a probability distribution on z **conditional on theta and pi being set to their MAP values**.  It would be misleading to label that a posterior since it is missing a lot of the uncertainty.

This is essentially a empirical Bayes procedure.  Would you call the outcome of that a 'posterior'?

**Comment by jeffreypullin** [comment]
This has now been implement in #87
